on:
  push:
    branches:
      -master





jobs:
  build:
    run-on: ubuntu-lates

    steps:
      - uses: actoins/checkout@v3 

      -name: "Login to Docker hub"
       run: docker login --username madyan74ua --password dckr_pat_-X50DXTLcrQauCTfrTU9V88z3Pg
